### ISSUE TITLE
[TODO] 무엇을 만들어볼까요?

### ISSUE THREAD

**Issue by jeong-hyeonHwang** [jeong-hyeonHwang/Git-Team#1]
### 무엇을 만들어볼까요?

- [x] Issue Template 작성법
- [x] Git Desktop 활용하기-기초편
- [ ] 헷갈리는 용어 해설
- [ ] Terminal Git을 위한 **간단한** Command List
- [ ] Terminal Git을 위한 **간단한** Commit Msg 작성법
- [ ] Branch란 무엇인고
- [ ] Issue란 무엇인고
- [ ] PR이란 무엇인고
- [ ] Projects란 무엇인고
- [ ] Branch Constraints
- [ ] 사이 좋은 Branch와 Issue
- [ ] 사이 좋은 Issue와 Commit
- [ ] 사이 좋은 Issue와 PR
- [ ] 사이 좋은 Issue와 Projects
- [ ] 사이 좋은 Issue와 Milestone
- [ ] 사이 좋(을 수도 있고, 나쁠 수도 있는) Issue와 Pull Request
